spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&serverTimezone=UTC
    password: 2002
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: mybatis-plus